export const WRONG_ANSWER_COUNT = 6;
export const DEFAULT_THEME_WORD_COUNT = 10;
export const MIN_THEME_GENERATION_WORD_COUNT = 5;
export const MAX_THEME_GENERATION_WORD_COUNT = 20;
export const MAX_RANDOM_GENERATED_WORD_COUNT = 10;
