import { WRONG_ANSWER_COUNT } from "../generate/constants";

export const THEME_NAME_MIN_LENGTH = 1;
export const THEME_NAME_MAX_LENGTH = 25;
export const THEME_PROMPT_MAX_LENGTH = 250;
export const CUSTOM_INSTRUCTIONS_MAX_LENGTH = 250;
export const THEME_USER_FEEDBACK_MAX_LENGTH = 250;
export const THEME_DESCRIPTION_MAX_LENGTH = 250;

export const THEME_WORD_INPUT_MAX_LENGTH = 64;
export const THEME_ANSWER_INPUT_MAX_LENGTH = 96;
export const THEME_WRONG_ANSWER_INPUT_MAX_LENGTH = 96;

export const THEME_MIN_WORD_COUNT = 1;
export const THEME_MAX_WORD_COUNT = 200;

export const THEME_MIN_WRONG_ANSWER_COUNT = 3;
export const THEME_MAX_WRONG_ANSWER_COUNT = WRONG_ANSWER_COUNT;

export const THEME_SAVE_REQUEST_ID_MAX_LENGTH = 128;
